name: Makefile CI
run-name: lemniskett/android-kernel-actions@v1.0.0





on:
  push:
    branches: [ "tiramisu" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: chmod +xX ./configure && bash ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck

